name: Build and push base Docker images

# Only build when the dockerfile has changed, otherwise scheduled on the first
# of each month
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'extras/docker/base/Dockerfile'
      - '.github/workflows/docker-base.yml'
  schedule:
    - cron: '0 5 1 * *'

env:
  REGISTRY_REPO: ${{ vars.REGISTRY_REPO || format('ghcr.io/{0}', github.repository) }}

jobs:
  path-context:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      HAS_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to DockerHub (optional)
        if: env.HAS_DOCKERHUB == 'true'
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: extras/docker/base/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ env.REGISTRY_REPO }}/base:latest,${{ env.REGISTRY_REPO }}/base:2.4-dev
